version: "2.3"
services:
  maria:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_USER: ${POSTGRES_USER:-user}
      MYSQL_PASSWORD: ${POSTGRES_DB:-password}
      MYSQL_DATABASE: ${POSTGRES_DB:-user}
    volumes:
      - maria_data:/var/lib/mysql
    healthcheck:
      test: echo "select 1;" | MYSQL_PWD=$${MYSQL_PASSWORD} mysql -u $${MYSQL_USER} -h maria $${POSTGRES_DB} || exit 1
  mysqld_exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: ${MYSQL_USER:-user}:${MYSQL_PASSWORD:-password}@(pg:3306)/${POSTGRES_DB:-user}
    network_mode: service:maria
  adminer:
    image: adminer
    depends_on: 
      - maria
    healthcheck:
      test: curl http://adminer:8080 || exit 1
volumes:
  maria_data:
