version: "2.3"
services:
  gitlab:
    image: gitlab/gitlab-ce:10.4.3-ce.0
    volumes:
      - ./gitlab:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      DB_HOST: db
      DB_PASSWORD: gitlab
      REDIS_HOST: redis
    ports:
      - 8443:443
      - 8081:80
      - "2222:22"
    depends_on:
      - db
      - redis
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: gitlabhq_production
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
  postgres-exporter:
    image: wrouesnel/postgres_exporter:v0.3.0
    environment:
      DATA_SOURCE_NAME: postgresql://gitlab:gitlab@localhost/gitlabhq_production?sslmode=disable
    depends_on: 
      - db
    network_mode: service:db
  redis:
    image: redis:alpine
  redis-exporter:
    image: oliver006/redis_exporter
    network_mode: service:redis
    depends_on:
      - redis
  node-exporter:
    image: quay.io/prometheus/node-exporter
  prometheus:
    image: quay.io/prometheus/prometheus:v2.1.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    healthcheck:
      test: wget --quiet --tries 1 -O /dev/null http://localhost:9090
    ports:
      - 9090:9090
volumes:
  prometheus_data:
  gitlab_logs:
  gitlab_data:
