---
global:
  scrape_interval: 15s
  scrape_timeout: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: redis
  static_configs:
  - targets:
    - redis-exporter:9121
- job_name: postgres
  static_configs:
  - targets:
    - postgres-exporter:9187
- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100
- job_name: gitlab-workhorse
  static_configs:
  - targets:
    - gitlab:9229
- job_name: gitlab-unicorn
  metrics_path: "/-/metrics"
  static_configs:
  - targets:
    - gitlab:8080
- job_name: gitlab-sidekiq
  static_configs:
  - targets:
    - gitlab:8082
- job_name: gitlab_monitor_database
  metrics_path: "/database"
  static_configs:
  - targets:
    - gitlab:9168
- job_name: gitlab_monitor_sidekiq
  metrics_path: "/sidekiq"
  static_configs:
  - targets:
    - gitlab:9168
- job_name: gitlab_monitor_process
  metrics_path: "/process"
  static_configs:
  - targets:
    - gitlab:9168
- job_name: gitaly
  static_configs:
  - targets:
    - gitlab:9236

